name: Intro to Github Actions

# what triggers make this workflow run test
on: 
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Install dependenciees
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run the server
        run: |
          pnpm run preview &
          sleep 5

      - name: Curl the server
        run: curl -I http://localhost:4173